config/routes.rb
Linker::Application.routes.draw do

  resources :feature_switches

  match 'ladmin/login' => 'ladmin#login', via: [:get, :post]
  match 'ladmin/logout' => 'ladmin#logout', via: [:get, :post]

  resources :users
  resources :groups do
    resources :links # Enables group/:id/link/new
    collection do
      post 'order_links'
    end
  end

  #match 'search' => 'links#index'
  get 'search' => 'links#index'
  get 'advanced_search' => 'links#advanced_search'
  resources :links do
    collection do
      get 'groups'
    end
  end

  get 'toggle_full_details' => 'links#toggle_full_details'
  get 'toggle_row_shading' => 'links#toggle_row_shading'

  get 'verify_link/:id', to: 'links#verify_link', as: :verify_link
  get 'unverify_link/:id', to: 'links#unverify_link', as: :unverify_link

  root "links#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :links, :dependent => :destroy
  validates_presence_of :group_name
  validates_size_of :group_name, :maximum => 20
  default_scope -> { order(group_name: :asc)}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :authorize, except: [:index, :show]

  def index
    @groups = Group.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    @members = Link.where(group_id: params[:id]).order(:position)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @group }
      format.json { render json: @members } # for ajax to show link members before deleting group.
    end
  end

  def order_links
    params[:link].each_with_index do |id, index|
      Link.where(id: id).update_all(['position = ?',index+1])
    end
    render nothing: true
  end

  def new
    @group = Group.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        flash[:notice] = 'Group was successfully created.'
        format.html { redirect_to(@group) }
        format.xml  { render xml: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.xml  { render xml: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    redirect_to Group.find(params[:id]).tap { |group|
      group.update!(group_params)
    }

  end

  def destroy
    @group = Group.find(params[:id])
    respond_to do |format|
      group_link_count= @group.links.count
      if @group.destroy
        flash[:notice] = "Group " + ((group_link_count > 0) ? "(and #{group_link_count} member links) " : "") + "was deleted"
        format.html { redirect_to(groups_url) }
        format.xml  { head :ok }
      else
        flash[:notice] = 'Error deleting group, not deleted.'
        format.html { redirect_to(groups_url) }
        format.xml  { render xml: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def group_params
    params.require(:group).permit(:group_name, :group_description)
  end

end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  %p
    = f.label :group_name
    %br/
    = f.text_field :group_name, options = {:autofocus => true, :required => true}
  %p
    = f.label :group_description
    %br/
    = f.text_field :group_description
  %p
    = f.submit "Save"

app/views/groups/edit.html.haml
%h3 Edit group
= render :partial => "form"

app/views/groups/index.html.haml
%br
%h3 Groups
%table
  %tr
    %th Group name
  - for group in @groups
    %tr
      %td= h group.group_name
      %td= link_to 'Edit', edit_group_path(group)
      -if group.links.count > 0
        %td= link_to 'Members', group, :remote => true, :data => {:show_group_members => true, :id => group.id, :name => group.group_name}
      -else
        %td= link_to 'Delete empty group', group, :method => :delete, :data => {confirm: 'Are you sure?'}

app/views/groups/new.html.haml
%h3 New group
= render :partial => "form"

app/views/groups/show.html.haml
%h3
  Group:
  = h @group.group_name
%p
  %b
    = h @group.group_description
Members:
%br/
- if @members.count.zero?
  %br/
  No members(links) in this category!
  %br/
  %br/
- else
  %ul#sortable
    - @members.each do |loop|
      = content_tag_for :li, loop do
        - construct_hyperlink(loop.url_address, loop.alt_text)
        = sanitize @address_url
        \- #{h @new_link_alt_text}            &nbsp;&nbsp;#{link_to 'details', link_path(loop), {"title" => loop.alt_text}}            &nbsp;&nbsp;#{link_to 'edit', edit_link_path(loop), {"title" => loop.alt_text}}

- if @members.count > 1
  Total= 
  %b
    #{@members.count}
  %br/
  %br/
= link_to "Add New Link for #{@group.group_name}", new_group_link_path(@group) #, "title" => 'Add a New Link'
%br/
- if @members.count > 1
  %br/
  Drag any member up or down to change its priority!
  %br/
  (Only saved if logged in).