config/routes.rb
Linker::Application.routes.draw do

  resources :feature_switches

  match 'ladmin/login' => 'ladmin#login', via: [:get, :post]
  match 'ladmin/logout' => 'ladmin#logout', via: [:get, :post]

  resources :users
  resources :groups do
    resources :links # Enables group/:id/link/new
    collection do
      post 'order_links'
    end
  end

  #match 'search' => 'links#index'
  get 'search' => 'links#index'
  get 'advanced_search' => 'links#advanced_search'
  resources :links do
    collection do
      get 'groups'
    end
  end

  get 'toggle_full_details' => 'links#toggle_full_details'
  get 'toggle_row_shading' => 'links#toggle_row_shading'

  get 'verify_link/:id', to: 'links#verify_link', as: :verify_link
  get 'unverify_link/:id', to: 'links#unverify_link', as: :unverify_link

  root "links#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  require 'digest/sha1'

  validates_presence_of     :username
  validates_uniqueness_of   :username
  validates_confirmation_of :password
  validate :password_non_blank

  def self.delete_one_admin(user)
    admin_count = User.where(admin: true).count
    if admin_count > 1
      user.delete
    else
      raise "You can't delete the only admin!"
    end
  end

  def self.authenticate(name, password)
    user = self.find_by(username: name)
    if user
      expected_password = encrypted_password(password, user.salt)
      if user.pwd_hashed != expected_password
        user = nil
      end
    end
    user
  end

  def password
    @password
  end

  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.pwd_hashed = User.encrypted_password(self.password, self.salt)
  end

  def is_admin
    admin ? 'Yes' : 'No'
  end

private
  def password_non_blank
    errors.add(:password, "Missing password") if pwd_hashed.blank?
  end

  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize_admin

  def index
    @users = User.all.order(username: :asc)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @user }
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:notice] = 'User '+ @user.username+ ' was successfully created.'
        format.html { redirect_to(action: "index") }
        format.xml  { render xml: @user, status: :created, location: @user }
      else
        format.html { render :action => "new" }
        format.xml  { render xml: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    redirect_to User.find(params[:id]).tap { |user|
      user.update!(user_params)
    }

  end

  def destroy
    @user = User.find(params[:id])
    begin
      if @user.admin
        User.delete_one_admin(@user)
        flash[:notice] = "User #{@user.username} deleted"
      else
        if User.all.count > 1
          @user.destroy
          flash[:notice] = "User #{@user.username} deleted"
        else
          raise "You can't delete the only user!"
        end
      end
    rescue Exception => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmationi, :admin)
  end

end

app/views/users/_admin_section.html.haml
%p
  = f.label :admin?
  %br/
  - if session[:admin]
    = f.check_box :admin
  - else
    = @user.is_admin

app/views/users/edit.html.haml
%h3 Editing user
= form_for(@user) do |f|
  -if @user.errors.any?
    %div#error_explanation
      %h2
        =pluralize(@user.errors.count, "error")+' '
        prohibited this user from being saved:
      %ul
      -@user.errors.full_messages.each do |msg|
        %li
          =msg
  %p
    = f.label :username, options = {:autofocus => true}
    %br/
    = f.text_field :username, options = {:required => true}
  = render 'admin_section', :f => f
  %p
    = f.submit "Update"
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
%h3 Users
%br

=link_to :feature_switches, feature_switches_path
%br
%br

%table
  %tr
    %th Username
    %th Admin?
  - for user in @users
    %tr
      %td= h user.username
      %td.column_align= h user.is_admin
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      - if session[:admin]
        %td= link_to 'Remove', user, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'Add user', new_user_path

app/views/users/new.html.haml
%h3 New user
= form_for(@user) do |f|
  -if @user.errors.any?
    %div#error_explanation
      %h2
        =pluralize(@user.errors.count, "error")+' '
        prohibited this user from being saved:
      %ul
      -@user.errors.full_messages.each do |msg|
        %li
          =msg
  %fieldset
    %legend
      Details.
    %p
      = f.label :username
      %br/
      = f.text_field :username, options = {:autofocus => true, :required => true}
    %p
      = f.label :password, 'Password'
      %br/
      = f.password_field :password, :size => 40
    %p
      = f.label :password_confirmation, 'Confirm'
      %br/
      = f.password_field :password_confirmation, :size => 40
    = render 'admin_section', :f => f
    %p
      = f.submit "Create"
= link_to 'Back', users_path

app/views/users/show.html.haml
%p
  %b Username:
  = h @user.username
%p
  %b Admin:
  = h @user.is_admin