config/routes.rb
Linker::Application.routes.draw do

  resources :feature_switches

  match 'ladmin/login' => 'ladmin#login', via: [:get, :post]
  match 'ladmin/logout' => 'ladmin#logout', via: [:get, :post]

  resources :users
  resources :groups do
    resources :links # Enables group/:id/link/new
    collection do
      post 'order_links'
    end
  end

  #match 'search' => 'links#index'
  get 'search' => 'links#index'
  get 'advanced_search' => 'links#advanced_search'
  resources :links do
    collection do
      get 'groups'
    end
  end

  get 'toggle_full_details' => 'links#toggle_full_details'
  get 'toggle_row_shading' => 'links#toggle_row_shading'

  get 'verify_link/:id', to: 'links#verify_link', as: :verify_link
  get 'unverify_link/:id', to: 'links#unverify_link', as: :unverify_link

  root "links#index"

end

app/models/link.rb
class Link < ActiveRecord::Base

  belongs_to :group
  validates_presence_of :url_address
  validates_presence_of :group_id
  validates_size_of :version_number, :maximum => 10 #, :allow_nil => true
  validates_uniqueness_of :url_address, scope: :group_id, message: 'already exists in that group'
  validate :url_address_not_just_http
  before_save :verify_url, if: :url_address_changed?
  acts_as_list

  def valid_get?
    HTTParty.get(url_address).code.between?(100,399) ? true : false
  rescue SocketError, URI::InvalidURIError
    false
  end

  def verify_url
    if valid_get?
      self.verified_date = Time.now
    end
  end

  def alt_text_or_url
    if alt_text == ''
      alt_text_or_url_address = url_address
    else
      alt_text_or_url_address = alt_text
    end
  end
end

def url_address_not_just_http
  errors.add(:url_address, "can't be just http://") if url_address == 'http://'
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_filter :authorize, except: [:index, :show, :advanced_search]

  def advanced_search
    @groups = Group.all
    @years = ((Date.today.year - 20)..Date.today.year).to_a
  end

  def toggle_row_shading
    if session[:group_shading] == 'true'
      session[:group_shading] = 'false'
    else
      session[:group_shading] = 'true'
    end
    render nothing: true
  end


  def toggle_full_details
    if session[:full_details] == 'true'
      session[:full_details] = 'false'
    else
      session[:full_details] = 'true'
    end
    render nothing: true
  end

  def verify_link
    @link = Link.find(params[:id])
    if @link.valid_get?
      @link.update({verified_date: Time.now})
      respond_to do |format|
        format.html { render action: "show", flash[:notice] => 'Valid URL'}
        format.js { render nothing: true }
      end
    else
      respond_to do |format|
        format.html { render action: "show", flash[:alert] => 'invalid URL', status: 422}
        format.js { render nothing: true }
      end
    end
  end

  def unverify_link
    @link = Link.find(params[:id])
    @link.verified_date = nil
    @link.save!
    respond_to do |format|
      format.html { render action: "show"}
    end
  end

  def index
    if (FeatureSwitch.where(name: 'links_index_scrollable_table', status: 'on').count) > 0
      @thead_scroller = "thead_scroller"
      @tbody_scrolling = "tbody_scrolling"
    end
    @from = PrepareSearch.start_date(params[:from] ||= '1991')
    @to = PrepareSearch.end_date(params[:to] ||= '2299')

    if params[:search_text_1st_phrase] # both simple and advanced search use this field.
      @words_1 = params[:search_text_1st_phrase]
      if params[:commit].downcase == 'advanced search'
        @join_operator = params[:join_operator].downcase
        @words_2 = params[:search_text_2nd_phrase]
        @text_search = PrepareSearch.text_search(@words_1, @join_operator, @words_2)
        @groups_comparison = PrepareSearch.groups(params[:groups])
        @version_information = { version: params[:version].to_i, version_comparison: params[:version_comparison], include_blank_version: params[:include_blank_version] }
        @version_comparison = PrepareSearch.versions(@version_information)
        @date_comparison = PrepareSearch.dates(@from, @to)
        @conditions = '1=1' + @groups_comparison+ @date_comparison + @text_search
        # + @version_comparison
      else
        @conditions = PrepareSearch.basic_search(@words_1)
      end
    else
      @conditions = ''
    end
    #@links = Link.where(@conditions).by_group_and_position
    #@links = Link.includes(:group).where(@conditions).references(:group).order('groups.group_name, links.position')
    @links = Link.joins(:group).where(@conditions).references(:group).order('groups.group_name, links.position')
    respond_to do |format|
      format.html
    end
  end

  def show
    @link = Link.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @link = Link.new
    # @link.content_date=Time.new().strftime("%m/%d/%Y")
    @link.content_date=Time.new().to_s[0,10]
    @link.url_address='http://'
    @groups = Group.all.collect { |g| [g.group_name, g.id] }
    @group_name =
      if params[:group_id]
        'for the '+Group.find(params[:group_id]).group_name + ' group.'
      else
        ''
      end
    respond_to do |format|
      format.html
    end
  end

  def edit
    @link = Link.find(params[:id])
    if @link.content_date.nil?
      @link.content_date=(Time.new().to_s)[0,10]
    end
    @groups = Group.all.collect { |g| [g.group_name, g.id] }
    @group_name =
      if params[:group_id]
        'for the '+Group.find(params[:group_id]).group_name + ' group.'
      else
        ''
      end
    respond_to do |format|
      format.html
    end
  end

  def create
    @link = Link.new(link_params)

    unless link_params[:content_date].nil?

      the_date = construct_date.to_date.strftime("%Y-%m-%d")
# %Y-%m-%d Date format required for date to save correctly AND tests not to fail !!! @link.content_date = Time.new().strftime("%Y/%m/%d") # %m/%d/%Y makes tests fail.
      @link.update!(content_date: the_date)

    end

    respond_to do |format|
      if @link.save
        unless @link.verified_date.nil?
          http_check_msg = 'and the url was verified as valid'
        else
          http_check_msg = 'however it was *not* possible to visit the url as given currently'
        end
        flash[:notice] = 'Link was successfully created, ' + http_check_msg
        format.html { redirect_to(@link) }
      else
        flash[:notice] = 'Error, The link was not created.'
        @groups = Group.all.collect { |g| [g.group_name, g.id] }
        format.html { render action: "new"}
      end
    end
  end

  def update
    this_link = Link.find(params[:id])
    this_link.update(link_params)
    this_link.tap { |link| link.update!(link_params) }
    the_date = construct_date #.to_date.strftime("%Y-%m-%d") # %Y-%m-%d Date format required for date to save correctly.
    this_link.update!(content_date: the_date)
    redirect_to this_link
  end

  def destroy
    @link = Link.find(params[:id])
    @link.destroy
    respond_to do |format|
      format.html { redirect_to(links_url) }
      format.js
    end
  end

  private

  def construct_date
    link_params[:content_date].to_s[6,4]+ '-' +
    link_params[:content_date].to_s[0,2]+ '-' +
    link_params[:content_date].to_s[3,2]
  end

  def link_params
    params
    .require(:link)
    .permit(:url_address, :group_id, :alt_text, :version_number, :position, :content_date, :verified_date)
  end

end

app/helpers/links_helper.rb
module LinksHelper
  def construct_hyperlink(link_url, link_alt_text='', size='long')
    @www_max_length = size == 'long' ? 69 : 19
    @alt_text_max_length = size == 'long' ? 85 : 35
    link_url= link_url.gsub('http://','').gsub('https://','')
    link_url_no_www= link_url.gsub('http://','').gsub('https://','').gsub('www.','')
    new_url= '<a href="http://' + link_url +'" title="' + link_url + '">'
    @address_url= link_url_no_www.length > @www_max_length ? (new_url + link_url_no_www[0..(@www_max_length+5)] + '...' + '</a>') : (new_url + link_url_no_www + '</a>')
    alt = link_alt_text.nil? ? '' : link_alt_text
    @new_link_alt_text= alt.length > @alt_text_max_length  ? (alt[0..(@alt_text_max_length-1)] + '...') : alt
    return @address_url, @new_link_alt_text
  end

  def group_name_for_link_form_title(group_id)
    'for the '+Group.find(group_id).group_name + ' group.'
  end

  def rotate_rows_color_group
    if session[:group_shading] == 'true' || params[:show]
      cycle('row_color_group_1 color_group_1', 'row_color_group_2 color_group_2', 'row_color_group_3 color_group_3')
    else
      cycle('row_color_group_1', 'row_color_group_2', 'row_color_group_3')
    end
  end

  def long_form(date)
    date.strftime('%m/%d/%Y')
  end

  def short_form(date)
    date.strftime('%Y')
  end

end

app/views/links/_alt_text_toggle.html.haml
%span{class: "show_hide shown"}
  = sanitize texts[0]
%span{class: "show_hide hidden"}
  = sanitize texts[1]

app/views/links/_links.html.haml
%span.spaced#shading_link
  Group Shading:
  - if session[:group_shading] == 'true'
    = render partial: "toggle_group_shading_link_bold", :locals => {:toggle_row_shading => '0'}
  - else
    = render partial: "toggle_group_shading_link_bold", :locals => {:toggle_row_shading => '1'}
%span.spaced
  - if session[:full_details] == 'true'
    = render partial: 'toggle_details_link_bold', :locals => {:txt => "Summary / <b>Details</b>", :show_hide => 'shown'}
    = render partial: 'toggle_details_link_bold', :locals => {:txt => "<b>Summary</b> / Details", :show_hide => 'hidden'}
  - else
    = render partial: 'toggle_details_link_bold', :locals => {:txt => "<b>Summary</b> / Details", :show_hide => 'shown'}
    = render partial: 'toggle_details_link_bold', :locals => {:txt => "Summary / <b>Details</b>", :show_hide => 'hidden'}

app/views/links/_search.html.haml
=form_tag(search_path, :method => "get") do
  = text_field_tag('search_text_1st_phrase', params[:search_text], options = {:type => 'search', :autofocus => true, :placeholder => 'Enter search term', :title => 'search'} )
  = submit_tag("Search")
  &nbsp;
=link_to('Advanced Search', advanced_search_path)
%br/

app/views/links/_toggle.html.haml
%span{class: "show_hide #{show_hide}"}
  %a{href: '#', :data => {toggle_description_length: 'toggle'}}
    = raw(txt)

app/views/links/_toggle_details_link_bold.html.haml
%span{class: "show_hide #{show_hide}"}
  %a{href: '#', :data => {toggle_description_length: 'toggle'}}
    = raw(txt)

app/views/links/_toggle_group_shading_link_bold.html.haml
%span{class: "show_hide shown_shading_link"}
  %a{href: '#', :data => {"toggle_group_row_shading" => 'toggle'}}
    - if toggle_row_shading == '0'
      %b
        Yes
      \/ No
    - else
      Yes
      %b
        \/ No
%span{class: "show_hide hidden_shading_link"}
  %a{href: '#', :data => {"toggle_group_row_shading" => 'toggle'}}
    - if toggle_row_shading == '1'
      %b
        Yes
      \/ No
    - else
      Yes
      %b
        \/ No

app/views/links/advanced_search.html.haml
/ Links:
%h3 Advanced Search
=form_tag(search_path, :method => "get") do
  %table{:border=>'10px'}
    %tr
      %td
        Groups:
        %br
        - @groups.each do |group|
          = check_box_tag('groups[]', group.id, 1)
          = group.group_name
          %br
      %td
        Search Text:
        %br
        &nbsp;
        = text_field_tag('search_text_1st_phrase', params[:search_text], options = {:type => 'search', :autofocus => true, :placeholder => 'first search term' })
        %br
        &nbsp;
        and
        = radio_button_tag "join_operator", 'and', :default
        or
        = radio_button_tag "join_operator", 'or'
        %br
        &nbsp;
        = text_field_tag('search_text_2nd_phrase', params[:search_text], options = {:type => 'search', :placeholder => 'additional search term' } )
        %br
        %br
        = 'From: '
        = select_tag "from", options_for_select(@years)
        %br
        = raw('To: &nbsp;&nbsp;&nbsp;&nbsp;')
        = select_tag "to", options_for_select(@years.reverse!)
        %br
        Include Blank Dates?
        = check_box_tag('include_blank_dates', '', 1)
        %br
        %br
        Version
        = select_tag "version_comparison", options_for_select(['>=',' >',' =','<=',' <','<>'])
        = text_field_tag(:version, '0', options = {:size => '4'})
        %br
        Include Blank Versions?
        = check_box_tag('include_blank_version', '', 1)
        %br
        %br
    %tr
      %td{:colspan=>'2'}
        %div{:align=>'center'}
          = submit_tag("Advanced Search")
          &nbsp;&nbsp;&nbsp;&nbsp;

app/views/links/destroy.js.erb
var element = document.getElementById("<%= @link.id %>");
element.parentNode.parentNode.remove();

app/views/links/edit.html.haml
%h3 Edit Link
= render :partial => "form"
= render :partial => "common_bits/alls_links"

app/views/links/index.html.haml
/ Links:
%span#main
  - tbl_class = session[:full_details] == "true" ? 'wide' : 'narrow'
  %table{class: tbl_class, data_links: 'true'}
    %thead{class: "#{@thead_scroller}"}
      %tr
        %td{colspan: "7"}
    %tbody{class: "#{@tbody_scrolling}"}
      %tr
        %td{colspan: "7"}
          .nav_links
            = render partial: 'links'
            = render partial: 'search'
      %tr{data_header_row: 'true'}
        %td Groups
        %td URL
        %td Ver.
        %td Added
        %td &nbsp;&nbsp;Verified&nbsp;&nbsp;
        // Extra spaces stops ajax bouncing with "verified..."
        %td Alt Text
        %td &nbsp;
      - row_bg_color_group = 'row_color_group_1'
      - current_group = ''
      - size = session[:full_details] == 'true' ? 'long' : 'short'
      - @links.each_with_index do |link, index|
        - construct_hyperlink(link.url_address, link.alt_text, 'long')
        - long_url = @address_url
        - construct_hyperlink(link.url_address, link.alt_text, 'short')
        - short_url = @address_url
        - if link.group.group_name != (current_group ||= '')
          - display_group = current_group = link.group.group_name
          - row_bg_color_group = rotate_rows_color_group
          - show_group_name = true
        - else
          - show_group_name = false
        %tr{class: "#{row_bg_color_group}"}
          %td
            - if show_group_name
              = link_to display_group, link.group, {title: link.group.group_description}
          %td
            %span#mainLink
              = render :partial => 'content_toggle', :locals => { :content => [long_url, short_url] }
          %td= link.version_number
          %td.column_align
            - if link.content_date
              = render :partial => 'content_toggle', :locals => { :content => [long_form(link.content_date), short_form(link.content_date)] }
          %td.column_align
            %span{id: "verify_link_#{link.id}"}
              - if link.verified_date
                - link_text = session[:full_details] == 'true' ? long_form(link.verified_date) : short_form(link.verified_date)
                = render :partial => 'link_toggle', :locals => { :content => [long_form(link.verified_date), short_form(link.verified_date)], :url => verify_link_path(id: link.id, table_row: index) }
              - else
                - if session[:user_id]
                  %a{href: "#", :data => {verifying_link: 'yes', id: link.id, table_row: link.id}}
                    verify
                - else
                  No
          %td
            = render :partial => 'content_toggle', :locals => { :content => [@new_link_alt_text, @new_link_alt_text[0..24]] }
          %td
            = link_to 'Details', link, {title: link.alt_text_or_url}
          - if session[:admin]
            %td
              = link_to 'X', link_path(link), method: :delete, id: link.id, data: { confirm: 'Are you sure?', remote: true }
%br/
%span.mainLinks= render partial: 'links'
%br/
%br/
%span{data_total: ''}
  = "Total Links = #{@links.count}"
%br/
%br/

app/views/links/new.html.haml
= render :partial => "form"
= render :partial => "common_bits/alls_links"

app/views/links/show.html.haml
%h3 Link
%p
  %b URL:&nbsp;
  %a{href: "#{@link.url_address}", target: "_blank"}
    = h @link.url_address
%p
  %b Version Number:
  = h @link.version_number
%p
  %b Alt text:
  = h @link.alt_text
%p
  %b Content Date:
  = long_form(@link.content_date) if @link.content_date
- if @link.verified_date
  %p
    %b Verified Date:
    = long_form(@link.verified_date)
    &nbsp;
    - if session[:admin]
      = link_to 'Unverify', unverify_link_path(@link)
- else
  %p
    - if session[:user_id]
      = link_to 'Verify', verify_link_path(@link)
%p
  %b Group:
  = h @link.group.group_name
%p
  = link_to 'Edit', edit_link_path(@link)
  = '|'
  = link_to 'Delete', link_path(@link), method: :delete, data: { :confirm => 'Are you sure?' }

app/views/links/unverify_link.js.erb
$("span#verify_link_<%=params['table_row']%>")
  .html('<a href="verify_link/<%=params['id']%>?table_row=<%=params['table_row']%>" data-remote="true" title="Reverify this link">REverify</a>');

app/views/links/verify_link.js.erb
<%- if @link.verified_date %>
  $("span#verify_link_<%=params['table_row']%>").html('<span class="done">Verified</span>');
<%- else %>
  $("span#verify_link_<%=params['table_row']%>").html('<span class="undone">Unverified</span>');
<%- end %>