config/routes.rb
Linker::Application.routes.draw do

  resources :feature_switches

  match 'ladmin/login' => 'ladmin#login', via: [:get, :post]
  match 'ladmin/logout' => 'ladmin#logout', via: [:get, :post]

  resources :users
  resources :groups do
    resources :links # Enables group/:id/link/new
    collection do
      post 'order_links'
    end
  end

  #match 'search' => 'links#index'
  get 'search' => 'links#index'
  get 'advanced_search' => 'links#advanced_search'
  resources :links do
    collection do
      get 'groups'
    end
  end

  get 'toggle_full_details' => 'links#toggle_full_details'
  get 'toggle_row_shading' => 'links#toggle_row_shading'

  get 'verify_link/:id', to: 'links#verify_link', as: :verify_link
  get 'unverify_link/:id', to: 'links#unverify_link', as: :unverify_link

  root "links#index"

end

app/views/layouts/application.html.haml
%head
  %title="#{controller.controller_name.capitalize} - #{controller.action_name}"
  = stylesheet_link_tag 'application'
  = javascript_include_tag "application"
  = csrf_meta_tag
  = favicon_link_tag 'favicon.ico'
%body{lang:'en'}
  - if (::Rails.env.downcase != 'production') or (session[:username])
    %h2
      - if ::Rails.env.downcase != 'production'
        =::Rails.env.downcase.capitalize
      - if session[:username]
        %span#divider
          |
        %span#username_display= session[:username]
        %span#divider
          |
        %span#logout
          = link_to 'Logout', :controller => :ladmin, :action => 'logout'
  #banner
    %h1= link_to 'Linker', root_path
  #columns
    #side
      .alink= link_to 'Links', links_path
      - if session[:user_id]
        .alink= link_to 'New Link', new_link_path
      .alink= link_to 'Groups', groups_path
      - if session[:user_id]
        .alink= link_to 'New Group', new_group_path
        .alink= link_to 'Admin', users_path
      - else
        .alink= link_to 'Login', :controller => :ladmin, :action => 'login'
    #main
      - if flash[:notice]
        %span.notice
          = flash[:notice]
        %br
      - if flash[:warning]
        %span.warning
          = flash[:warning]
        %br
      - [@group,@link].compact.each do |model|
        - if model.errors.any?
          %span.errorExplanation
            %ul
              - model.errors.full_messages.each do |msg|
                %li
                  =msg
        - else
          %br
          %br
      = yield :layout